AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  http_api_gateway_demo

  Sample SAM Template for http_api_gateway_demo

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello-world/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /ibis/v2/{proxy+}
            Method: ANY
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  HelloWorldAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ibis/v2/"
  HelloWorldFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
